"""Provide notebook-first interactive function plotting."""

from __future__ import annotations

from .figure import (
    AudioPlaybackError,
    AudioPlaybackState,
    CurvePlotHandle,
    FigureHandle,
    FigureView,
    InfoHandle,
    LegendItem,
    LegendMarker,
    PLOT_NAMED_COLOR_HEX,
    PLOT_NAMED_COLORS,
    PlotHandle,
    PlotStyle,
    ViewHandle,
    PlottingError,
    FigureNotFoundError,
    InfoNotFoundError,
    PlotNotFoundError,
    ViewNotFoundError,
)
from .plot_node import PlotCompilationError, PlotShapeError
from .specs import PlotSpecError
from .display import FigureDisplayGeneration
from .layout import (
    CustomLayout,
    DefaultFigureLayout,
    EventBridgeWidget,
    FigureLayout,
    FigureLayoutParts,
    LayoutValidationError,
    ResponsiveSidebarLayout,
)
from .interactive import (
    plot,
    temperature_plot,
    contour_plot,
    domain_plot,
    parametric_plot,
    list_plot,
    get_plot,
    info,
    figure,
    current_figure,
    set_current_figure,
)
from .session import get_session

__all__ = [
    "FigureHandle",
    "FigureView",
    "InfoHandle",
    "CurvePlotHandle",
    "AudioPlaybackState",
    "LegendItem",
    "LegendMarker",
    "PLOT_NAMED_COLOR_HEX",
    "PLOT_NAMED_COLORS",
    "PlotHandle",
    "PlotStyle",
    "ViewHandle",
    "PlottingError",
    "AudioPlaybackError",
    "FigureNotFoundError",
    "InfoNotFoundError",
    "PlotNotFoundError",
    "ViewNotFoundError",
    "PlotCompilationError",
    "PlotShapeError",
    "PlotSpecError",
    "FigureLayout",
    "FigureLayoutParts",
    "ResponsiveSidebarLayout",
    "DefaultFigureLayout",
    "CustomLayout",
    "LayoutValidationError",
    "EventBridgeWidget",
    "FigureDisplayGeneration",
    "plot",
    "temperature_plot",
    "contour_plot",
    "domain_plot",
    "parametric_plot",
    "list_plot",
    "get_plot",
    "info",
    "figure",
    "current_figure",
    "set_current_figure",
    "get_session",
]
